observer:
  hosts:
    observer1:
      ansible_ssh_private_key_file: "my-key-location/id_rsa"
      ansible_host: 
      ansible_user: my-user
      ansible_sudo_password: ""
workers:
  hosts:
    worker1:
      ansible_host: 
      ansible_sudo_password: ""
      ansible_become: true
    worker2:
      ansible_host: localhost
      ansible_connection: local
      ansible_user: 
      ansible_sudo_password: ""
      ansible_become: true

mac_workers:
  hosts:
    <mac_worker_name>:
      ansible_ssh_private_key_file: ""
      ansible_host: 
      ansible_user: penguaman
      ansible_sudo_password: ""
      ansible_password: ""
      ansible_python_interpreter: "/Users/<>/.local/pipx/shared/bin/python"